[project]
name = "automated-research"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.120.0",
    "langchain>=1.0.2",
    "langgraph>=1.0.1",
]
